export interface UserProfile {
  user_id: number;
  user_email: string;
  user_fname: string;
  user_mname?: string | null;
  user_lname: string;
  suffix_name?: string | null;
  nickname?: string | null;
  user_contact: string;
  user_province: string;
  user_city: string;
  user_brgy: string;
  user_department?: number | null;
  user_sss?: string | null;
  user_philhealth?: string | null;
  user_tin?: string | null;
  user_pagibig?: string | null;
  user_position: string;
  employment_status_id?: number | null;
  user_dateOfHire: string;
  user_tags?: string | null;
  user_bday?: string | null;
  gender?: string | null;
  civil_status?: string | null;
  nationality?: string | null;
  citizenship?: string | null;
  place_of_birth?: string | null;
  blood_type?: string | null;
  religion?: string | null;
  spouse_name?: string | null;
  role_id?: number | null;
  user_image?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_number?: string | null;
  is_employee?: boolean;
  employee_type_id?: number | null;
  department_name?: string | null;
  employment_status_name?: string | null;
}
